# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 's28_qt3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 528)
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setGeometry(QtCore.QRect(50, 30, 151, 16))
        self.lb1.setObjectName("lb1")
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setGeometry(QtCore.QRect(280, 30, 161, 16))
        self.lb2.setObjectName("lb2")
        self.pb1 = QtWidgets.QPushButton(Form)
        self.pb1.setGeometry(QtCore.QRect(70, 120, 93, 28))
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(Form)
        self.pb2.setGeometry(QtCore.QRect(300, 120, 93, 28))
        self.pb2.setObjectName("pb2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb1.setText(_translate("Form", "Our label in widow"))
        self.lb2.setText(_translate("Form", "Second label in window"))
        self.pb1.setText(_translate("Form", "Our buttin"))
        self.pb2.setText(_translate("Form", "Sec button"))
